# Generated by Django 2.2.4 on 2020-09-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_file', models.ImageField(upload_to='images/')),
                ('date_of_upload', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
